# Generated by Django 3.2.3 on 2021-05-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='features',
            field=models.BooleanField(null=True),
        ),
    ]
