# Generated by Django 3.2.3 on 2021-05-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_post_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='features',
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
